import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1721000000000 implements MigrationInterface {
    name = 'InitialSchema1721000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "wing_participation_settings" ("id" SERIAL NOT NULL, "year" integer NOT NULL, "isAllowed" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_2c717e44baa3025b127d6d1fc2e" UNIQUE ("year"), CONSTRAINT "PK_832682fa5101d519959e3f118f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_roomtype_enum" AS ENUM('single', 'double', 'triple')`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_status_enum" AS ENUM('available', 'maintenance', 'occupied')`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" SERIAL NOT NULL, "hostelId" integer NOT NULL, "roomNumber" character varying NOT NULL, "floor" integer, "wing" character varying, "capacity" integer NOT NULL, "roomType" "public"."rooms_roomtype_enum" NOT NULL DEFAULT 'double', "status" "public"."rooms_status_enum" NOT NULL DEFAULT 'available', CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."hostels_gendertype_enum" AS ENUM('male', 'female', 'co-ed')`);
        await queryRunner.query(`CREATE TABLE "hostels" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "genderType" "public"."hostels_gendertype_enum" NOT NULL, CONSTRAINT "UQ_62f21122ecb435dd9d0680192ca" UNIQUE ("name"), CONSTRAINT "PK_2d7d9386d693449e9857576d246" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "creatorId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "groupPreferences" integer array NOT NULL DEFAULT '{}', CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_memberships_status_enum" AS ENUM('pending', 'accepted', 'declined')`);
        await queryRunner.query(`CREATE TABLE "group_memberships" ("groupId" integer NOT NULL, "userId" uuid NOT NULL, "status" "public"."group_memberships_status_enum" NOT NULL DEFAULT 'pending', "invitedAt" TIMESTAMP NOT NULL DEFAULT now(), "respondedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_271402eee28958172111ad1523f" PRIMARY KEY ("groupId", "userId"))`);
        await queryRunner.query(`CREATE TYPE "public"."students_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TABLE "students" ("userId" uuid NOT NULL, "rollNumber" character varying NOT NULL, "fullName" character varying NOT NULL, "year" integer NOT NULL, "gender" "public"."students_gender_enum" NOT NULL DEFAULT 'male', "program" character varying, "applicationTimestamp" TIMESTAMP, "hasSubmitted" boolean NOT NULL DEFAULT false, "applicationStatus" character varying NOT NULL DEFAULT 'NONE', "hostelPreferences" integer array NOT NULL DEFAULT '{}', "allocatedRoomId" integer, "currentRoomId" integer, CONSTRAINT "UQ_82b55075370818970f61b122fa3" UNIQUE ("rollNumber"), CONSTRAINT "PK_e0208b4f964e609959aff431bf9" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('student', 'warden')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'student', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" SERIAL NOT NULL, "key" character varying NOT NULL, "value" character varying NOT NULL, CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."swap_requests_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled', 'completed', 'expired')`);
        await queryRunner.query(`CREATE TYPE "public"."swap_requests_swaptype_enum" AS ENUM('direct', 'open', 'chain')`);
        await queryRunner.query(`CREATE TABLE "swap_requests" ("id" SERIAL NOT NULL, "requesterId" uuid NOT NULL, "targetStudentId" uuid, "requesterRoomId" integer NOT NULL, "targetRoomId" integer, "status" "public"."swap_requests_status_enum" NOT NULL DEFAULT 'pending', "swapType" "public"."swap_requests_swaptype_enum" NOT NULL DEFAULT 'direct', "chainId" character varying, "reason" text, "rejectionReason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, CONSTRAINT "PK_4a3a8b292e0e8df37acbc47e648" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."swap_history_executiontype_enum" AS ENUM('direct', 'chain')`);
        await queryRunner.query(`CREATE TABLE "swap_history" ("id" SERIAL NOT NULL, "studentId" uuid NOT NULL, "previousRoomId" integer NOT NULL, "newRoomId" integer NOT NULL, "chainId" character varying, "swapRequestId" integer, "executionType" "public"."swap_history_executiontype_enum" NOT NULL DEFAULT 'direct', "chainDetails" jsonb, "executedById" uuid NOT NULL, "executedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_409675d518508d6a7329f302179" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_invitations_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "roommate_invitations" ("id" SERIAL NOT NULL, "senderId" uuid NOT NULL, "receiverId" uuid NOT NULL, "groupId" integer, "status" "public"."roommate_invitations_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_995f86e115f5aeecece26c07013" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_roommate_invitations_receiver_accepted" ON "roommate_invitations" ("receiverId") WHERE status = 'accepted'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_roommate_invitations_sender_accepted" ON "roommate_invitations" ("senderId") WHERE status = 'accepted'`);
        await queryRunner.query(`CREATE TYPE "public"."allocation_runs_status_enum" AS ENUM('queued', 'running', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."allocation_runs_allocationmode_enum" AS ENUM('group_based', 'fcfs', 'wing_fcfs', 'global_optimization')`);
        await queryRunner.query(`CREATE TABLE "allocation_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "triggeredById" uuid NOT NULL, "status" "public"."allocation_runs_status_enum" NOT NULL DEFAULT 'queued', "allocationMode" "public"."allocation_runs_allocationmode_enum" NOT NULL DEFAULT 'group_based', "rulesSnapshot" jsonb, "totalStudents" integer NOT NULL DEFAULT '0', "allocatedStudents" integer NOT NULL DEFAULT '0', "averageHappiness" double precision NOT NULL DEFAULT '0', "errorMessage" character varying, "finalized" boolean NOT NULL DEFAULT false, "metrics" jsonb, "targetYears" jsonb, "targetPrograms" jsonb, "startTime" TIMESTAMP NOT NULL DEFAULT now(), "endTime" TIMESTAMP, CONSTRAINT "PK_e33e146d4eb0d0629fe71ea2b44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "allocation_rules" ("id" SERIAL NOT NULL, "hostelId" integer, "year" integer, "roomType" character varying, "wing" character varying, "isAllowed" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '0', "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bca39bc68bb87287544880c9d9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "allocation_results" ("id" SERIAL NOT NULL, "runId" character varying NOT NULL, "studentId" uuid NOT NULL, "roomId" integer, "hostelName" character varying, "roomNumber" character varying, "wing" character varying, "floor" integer, "groupId" integer, "reason" character varying, "isLocked" boolean NOT NULL DEFAULT false, "happiness" integer NOT NULL DEFAULT '50', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6bdd9cadfa0e050d276747efac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."administrative_actions_actiontype_enum" AS ENUM('EVICTION', 'ALLOCATION', 'PUBLISH_RUN')`);
        await queryRunner.query(`CREATE TABLE "administrative_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actionType" "public"."administrative_actions_actiontype_enum" NOT NULL, "performedBy" character varying NOT NULL, "description" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "snapshot" jsonb NOT NULL, "metadata" jsonb, "isReverted" boolean NOT NULL DEFAULT false, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17178785ef0f464acbf505b3245" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "allocation_decisions" ("id" SERIAL NOT NULL, "runId" uuid NOT NULL, "studentId" uuid NOT NULL, "decisionOrder" integer NOT NULL, "availableRooms" jsonb NOT NULL, "constraintsApplied" jsonb NOT NULL, "groupId" integer, "groupAllocationStrategy" character varying, "selectedRoomId" integer, "decisionReason" character varying NOT NULL, "happinessScore" integer NOT NULL DEFAULT '50', "alternativesConsidered" jsonb, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8497f50f947cb89794e946463b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_7ea81bd15cff0b6a7a50814095b" FOREIGN KEY ("hostelId") REFERENCES "hostels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_accb24ba8f4f213f33d08e2a20f" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_a434c0d46f4b97696924ecdd176" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_ae52b7a8e0e084d7945522ef762" FOREIGN KEY ("userId") REFERENCES "students"("userId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_e0208b4f964e609959aff431bf9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_a70bb43df1ed8035181e936d223" FOREIGN KEY ("allocatedRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_ac56f8d958a8c5583520810a954" FOREIGN KEY ("currentRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_210665e7bf32c2bf89e3123e03a" FOREIGN KEY ("requesterId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_36dada5c53523ab4445fe1cdcd8" FOREIGN KEY ("targetStudentId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_26e26c8abb60abeaacef7290277" FOREIGN KEY ("requesterRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_f7ecb386b17068e90dae501d672" FOREIGN KEY ("targetRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_history" ADD CONSTRAINT "FK_47210dcf89d196cd35af8a34058" FOREIGN KEY ("studentId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_history" ADD CONSTRAINT "FK_05294928528291ecb26d2b5970d" FOREIGN KEY ("previousRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_history" ADD CONSTRAINT "FK_4743bf3d5a6236d3d89e52e9051" FOREIGN KEY ("newRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_history" ADD CONSTRAINT "FK_1db6606c8d032f28980266e3f2c" FOREIGN KEY ("executedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_history" ADD CONSTRAINT "FK_5c76ba0309a3a0dc8fbe96be226" FOREIGN KEY ("swapRequestId") REFERENCES "swap_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_invitations" ADD CONSTRAINT "FK_695287ca25593813fc28e05d5b0" FOREIGN KEY ("senderId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_invitations" ADD CONSTRAINT "FK_47feecc5f76eee41a195d599f0b" FOREIGN KEY ("receiverId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_invitations" ADD CONSTRAINT "FK_84e2b6093a22ec7d0730e93a777" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_runs" ADD CONSTRAINT "FK_47a17d9362bca106bda37e91479" FOREIGN KEY ("triggeredById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_rules" ADD CONSTRAINT "FK_8db563b202c52737b3b7085b896" FOREIGN KEY ("hostelId") REFERENCES "hostels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_results" ADD CONSTRAINT "FK_9684981c783c4b4639dd162714f" FOREIGN KEY ("studentId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_results" ADD CONSTRAINT "FK_2c13efe33a930757cddd6e931bb" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_results" ADD CONSTRAINT "FK_358e78d7d9e75dd43c8a55641f6" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" ADD CONSTRAINT "FK_ab91cc30bf6d893219639974110" FOREIGN KEY ("runId") REFERENCES "allocation_runs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" ADD CONSTRAINT "FK_f8ab73e85b2028fb6b0dd370e13" FOREIGN KEY ("studentId") REFERENCES "students"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" ADD CONSTRAINT "FK_4958147e9447893040844a4847b" FOREIGN KEY ("selectedRoomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" ADD CONSTRAINT "FK_00db49ef73cfc83e35113f40585" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "allocation_decisions" DROP CONSTRAINT "FK_00db49ef73cfc83e35113f40585"`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" DROP CONSTRAINT "FK_4958147e9447893040844a4847b"`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" DROP CONSTRAINT "FK_f8ab73e85b2028fb6b0dd370e13"`);
        await queryRunner.query(`ALTER TABLE "allocation_decisions" DROP CONSTRAINT "FK_ab91cc30bf6d893219639974110"`);
        await queryRunner.query(`ALTER TABLE "allocation_results" DROP CONSTRAINT "FK_358e78d7d9e75dd43c8a55641f6"`);
        await queryRunner.query(`ALTER TABLE "allocation_results" DROP CONSTRAINT "FK_2c13efe33a930757cddd6e931bb"`);
        await queryRunner.query(`ALTER TABLE "allocation_results" DROP CONSTRAINT "FK_9684981c783c4b4639dd162714f"`);
        await queryRunner.query(`ALTER TABLE "allocation_rules" DROP CONSTRAINT "FK_8db563b202c52737b3b7085b896"`);
        await queryRunner.query(`ALTER TABLE "allocation_runs" DROP CONSTRAINT "FK_47a17d9362bca106bda37e91479"`);
        await queryRunner.query(`ALTER TABLE "roommate_invitations" DROP CONSTRAINT "FK_84e2b6093a22ec7d0730e93a777"`);
        await queryRunner.query(`ALTER TABLE "roommate_invitations" DROP CONSTRAINT "FK_47feecc5f76eee41a195d599f0b"`);
        await queryRunner.query(`ALTER TABLE "roommate_invitations" DROP CONSTRAINT "FK_695287ca25593813fc28e05d5b0"`);
        await queryRunner.query(`ALTER TABLE "swap_history" DROP CONSTRAINT "FK_5c76ba0309a3a0dc8fbe96be226"`);
        await queryRunner.query(`ALTER TABLE "swap_history" DROP CONSTRAINT "FK_1db6606c8d032f28980266e3f2c"`);
        await queryRunner.query(`ALTER TABLE "swap_history" DROP CONSTRAINT "FK_4743bf3d5a6236d3d89e52e9051"`);
        await queryRunner.query(`ALTER TABLE "swap_history" DROP CONSTRAINT "FK_05294928528291ecb26d2b5970d"`);
        await queryRunner.query(`ALTER TABLE "swap_history" DROP CONSTRAINT "FK_47210dcf89d196cd35af8a34058"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_f7ecb386b17068e90dae501d672"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_26e26c8abb60abeaacef7290277"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_36dada5c53523ab4445fe1cdcd8"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_210665e7bf32c2bf89e3123e03a"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_ac56f8d958a8c5583520810a954"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_a70bb43df1ed8035181e936d223"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_e0208b4f964e609959aff431bf9"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_ae52b7a8e0e084d7945522ef762"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_a434c0d46f4b97696924ecdd176"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_accb24ba8f4f213f33d08e2a20f"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_7ea81bd15cff0b6a7a50814095b"`);
        await queryRunner.query(`DROP TABLE "allocation_decisions"`);
        await queryRunner.query(`DROP TABLE "administrative_actions"`);
        await queryRunner.query(`DROP TYPE "public"."administrative_actions_actiontype_enum"`);
        await queryRunner.query(`DROP TABLE "allocation_results"`);
        await queryRunner.query(`DROP TABLE "allocation_rules"`);
        await queryRunner.query(`DROP TABLE "allocation_runs"`);
        await queryRunner.query(`DROP TYPE "public"."allocation_runs_allocationmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."allocation_runs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_roommate_invitations_sender_accepted"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_roommate_invitations_receiver_accepted"`);
        await queryRunner.query(`DROP TABLE "roommate_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_invitations_status_enum"`);
        await queryRunner.query(`DROP TABLE "swap_history"`);
        await queryRunner.query(`DROP TYPE "public"."swap_history_executiontype_enum"`);
        await queryRunner.query(`DROP TABLE "swap_requests"`);
        await queryRunner.query(`DROP TYPE "public"."swap_requests_swaptype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."swap_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_gender_enum"`);
        await queryRunner.query(`DROP TABLE "group_memberships"`);
        await queryRunner.query(`DROP TYPE "public"."group_memberships_status_enum"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "hostels"`);
        await queryRunner.query(`DROP TYPE "public"."hostels_gendertype_enum"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_roomtype_enum"`);
        await queryRunner.query(`DROP TABLE "wing_participation_settings"`);
    }
}
